packages:
  - playground
  - docs
  - packages/*
  - examples/*
catalog:
  hono: ^4.7.5
  node-notifier: ^10.0.1
  puppeteer: ^24.4.0
  puppeteer-extra: ^3.3.6
  puppeteer-extra-plugin-stealth: ^2.11.2
catalogs:
  cli:
    '@antfu/eslint-config': ^4.10.1
    '@antfu/ni': ^24.1.0
    '@hono/vite-build': ^1.3.0
    '@hono/vite-dev-server': ^0.19.0
    bumpp: ^10.1.0
    eslint: ^9.22.0
    lint-staged: ^15.5.0
    simple-git-hooks: ^2.11.1
    tsx: ^4.19.3
    typescript: ^5.8.2
    vite: ^6.2.1
  inlined:
    '@antfu/utils': ^9.1.0
  testing:
    vitest: ^3.0.8
    vitest-package-exports: ^0.1.1
    yaml: ^2.7.0
  types:
    '@types/node': ^22.13.10
  utils:
    tinyexec: ^0.3.2
onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
